Output ../../doc/img/app-new.gif

Set FontSize 24
Set Width 1200
Set Height 600

# Command
Type "hexago app new"
Sleep 500ms
Enter

Sleep 1s

# Write app Name
Type "UserREST"
Sleep 1000ms
Enter

Sleep 1s

# Write app folder name
Type "userrest"
Sleep 1000ms
Enter

Sleep 1s

# Select Domain
Enter
Sleep 1s

# Select interface to implement
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Enter

# Assert port
Sleep 1s
Left
Sleep 500ms
Enter

Sleep 2s