Output ../../doc/img/pkg-new.gif

Set FontSize 24
Set Width 1200
Set Height 600

# Command
Type "hexago pkg new"
Sleep 500ms
Enter

Sleep 1s

# Write package name
Type "Logger"
Sleep 1000ms
Enter

Sleep 1s

# Write package folder name
Type "logger"
Sleep 1000ms
Enter

Sleep 1s

# Select interface to implement
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Enter

# Assert port
Sleep 1s
Left
Sleep 500ms
Enter

# Select Global
Sleep 1s
Down
Sleep 500ms
Enter


Sleep 2s